site_name: Williamwu
site_description: Personal Blog, Projects and Research Portfolio
site_author: William Wu
site_url: https://empandme.github.io/Personal-Blog/

theme:
  name: material
  
  palette:
  - scheme: default
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - search.highlight
  - search.suggest
  - content.code.copy

  plugins:
    search

  markdown_extensions:
    admonition
    attr_list
    md_in_html